# Generated by Django 4.1.1 on 2022-12-01 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='ctreated_at',
            new_name='created_at',
        ),
    ]
